include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - prefer_const_constructors
    - public_member_api_docs
    - prefer_final_locals
