import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';
import 'package:crypto/crypto.dart' as sha;
import 'native_crypto_bridge.dart';
import 'native_crypto_bridge_selector.dart';

/// Represents one independent Shamir recovery share artifact.
class RecoveryShare {
  /// The raw SSS share bytes (x-coordinate + share data).
  final Uint8List shareBytes;

  /// The self-contained Base32-encoded string representing this share,
  /// formatted with hyphens for easy transcription.
  final String encodedShare;

  /// The epoch identifier (UUID v4) for this generation of shares.
  final String epochId;

  /// The reconstruction threshold M.
  final int threshold;

  /// The total number of shares N.
  final int totalShares;

  RecoveryShare({
    required this.shareBytes,
    required this.encodedShare,
    required this.epochId,
    required this.threshold,
    required this.totalShares,
  });
}

/// Helper class to perform Shamir's Secret Sharing operations on Recovery Keys.
class ShamirRecovery {
  final NativeCryptoBridge _bridge;
  static const _alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

  ShamirRecovery([NativeCryptoBridge? bridge])
      : _bridge = bridge ?? NativeCryptoBridgeImpl();

  /// Splits [recoveryKey] string (e.g. Base32 key generated by the Emergency Kit)
  /// into [n] shares with a reconstruction threshold of [m].
  ///
  /// Returns a record containing the list of [n] [RecoveryShare]s and the [epochId] UUID.
  ({List<RecoveryShare> shares, String epochId}) splitRecoveryKey({
    required String recoveryKey,
    required int m,
    required int n,
  }) {
    if (m < 2 || m > n || n > 255) {
      throw ArgumentError('Invalid threshold $m or total shares $n');
    }

    // Clean and decode the recovery key to raw bytes (20 bytes)
    final cleaned = recoveryKey.replaceAll('-', '').toUpperCase();
    final secretBytes = _decodeRecoveryKeyToBytes(cleaned);

    final epochBytes = _generateUuidV4();
    final epochStr = _uuidBytesToString(epochBytes);

    // Call SSS split via native FFI/wasm bridge
    final rawShares = _bridge.shamirSplit(
      secret: secretBytes,
      m: m,
      n: n,
    );

    final shares = <RecoveryShare>[];
    for (final rawShare in rawShares) {
      // Encode self-contained packet:
      // [16 bytes epoch UUID] [1 byte M] [1 byte N] [21 bytes share] [2 bytes checksum] = 41 bytes
      final packet = Uint8List(41);
      packet.setRange(0, 16, epochBytes);
      packet[16] = m;
      packet[17] = n;
      packet.setRange(18, 39, rawShare);

      // Compute checksum
      final checksum = _computeChecksum(packet.sublist(0, 39));
      packet[39] = checksum[0];
      packet[40] = checksum[1];

      final base32Str = _toBase32(packet);
      final formattedStr = _formatWithHyphens(base32Str);

      shares.add(RecoveryShare(
        shareBytes: rawShare,
        encodedShare: formattedStr,
        epochId: epochStr,
        threshold: m,
        totalShares: n,
      ));
    }

    return (shares: shares, epochId: epochStr);
  }

  /// Reconstructs the recovery key string from a list of collected [shares].
  ///
  /// Requires at least [m] valid shares from the same epoch.
  /// Throws [ArgumentError] if parsing or reconstruction fails.
  String combineShares(List<String> encodedShares) {
    if (encodedShares.isEmpty) {
      throw ArgumentError('No shares provided');
    }

    final parsedShares = <_ParsedShare>[];
    String? expectedEpoch;
    int? expectedM;
    int? expectedN;

    for (final enc in encodedShares) {
      final packet = _fromBase32(enc);
      if (packet.length != 41) {
        throw ArgumentError('Invalid share length: expected 41 bytes, got ${packet.length}');
      }

      // Verify checksum
      final computed = _computeChecksum(packet.sublist(0, 39));
      if (packet[39] != computed[0] || packet[40] != computed[1]) {
        throw ArgumentError('Checksum verification failed. Check for typos in the share.');
      }

      final epochBytes = packet.sublist(0, 16);
      final epochStr = _uuidBytesToString(epochBytes);
      final m = packet[16];
      final n = packet[17];
      final rawShare = packet.sublist(18, 39);

      if (expectedEpoch == null) {
        expectedEpoch = epochStr;
        expectedM = m;
        expectedN = n;
      } else if (epochStr != expectedEpoch) {
        throw ArgumentError('Provided shares are from different recovery key generations (epochs)');
      }

      parsedShares.add(_ParsedShare(rawShare, m, n));
    }

    if (parsedShares.length < expectedM!) {
      throw ArgumentError('Insufficient shares: received ${parsedShares.length}, need at least $expectedM');
    }

    // Call SSS combine via bridge
    final secretBytes = _bridge.shamirCombine(
      shares: parsedShares.map((p) => p.rawBytes).toList(),
    );

    // Encode secret back to standard Recovery Key Base32 format (XXXX-XXXX-...)
    final rkBase32 = _toBase32(secretBytes);
    return _formatWithHyphens(rkBase32);
  }

  // --- Internals & Encoding ---

  static Uint8List _decodeRecoveryKeyToBytes(String cleaned) {
    if (cleaned.length != 32) {
      throw ArgumentError('Invalid recovery key length');
    }
    final result = Uint8List(20);
    var bitBuffer = 0;
    var bitCount = 0;
    var resultIndex = 0;
    for (var i = 0; i < cleaned.length; i++) {
      final index = _alphabet.indexOf(cleaned[i]);
      if (index == -1) {
        throw ArgumentError('Invalid character in recovery key');
      }
      bitBuffer = (bitBuffer << 5) | index;
      bitCount += 5;
      if (bitCount >= 8) {
        result[resultIndex++] = (bitBuffer >> (bitCount - 8)) & 255;
        bitCount -= 8;
      }
    }
    return result;
  }

  static Uint8List _generateUuidV4() {
    final random = Random.secure();
    final bytes = Uint8List(16);
    for (var i = 0; i < 16; i++) {
      bytes[i] = random.nextInt(256);
    }
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    return bytes;
  }

  static String _uuidBytesToString(Uint8List bytes) {
    final buffer = StringBuffer();
    for (var i = 0; i < 16; i++) {
      if (i == 4 || i == 6 || i == 8 || i == 10) {
        buffer.write('-');
      }
      buffer.write(bytes[i].toRadixString(16).padLeft(2, '0'));
    }
    return buffer.toString().toUpperCase();
  }

  static Uint8List _computeChecksum(Uint8List data) {
    final hash = sha.sha256.convert(data);
    return Uint8List.fromList(hash.bytes.sublist(0, 2));
  }

  static String _toBase32(Uint8List bytes) {
    var bitBuffer = 0;
    var bitCount = 0;
    final buffer = StringBuffer();
    for (final byte in bytes) {
      bitBuffer = (bitBuffer << 8) | byte;
      bitCount += 8;
      while (bitCount >= 5) {
        final index = (bitBuffer >> (bitCount - 5)) & 31;
        buffer.write(_alphabet[index]);
        bitCount -= 5;
      }
    }
    if (bitCount > 0) {
      final index = (bitBuffer << (5 - bitCount)) & 31;
      buffer.write(_alphabet[index]);
    }
    return buffer.toString();
  }

  static Uint8List _fromBase32(String base32Str) {
    final cleaned = base32Str.replaceAll('-', '').toUpperCase();
    var bitBuffer = 0;
    var bitCount = 0;
    final result = <int>[];
    for (var i = 0; i < cleaned.length; i++) {
      final index = _alphabet.indexOf(cleaned[i]);
      if (index == -1) {
        throw ArgumentError('Invalid character in Base32 string');
      }
      bitBuffer = (bitBuffer << 5) | index;
      bitCount += 5;
      if (bitCount >= 8) {
        result.add((bitBuffer >> (bitCount - 8)) & 255);
        bitCount -= 8;
      }
    }
    return Uint8List.fromList(result);
  }

  static String _formatWithHyphens(String raw) {
    final formatted = StringBuffer();
    for (var i = 0; i < raw.length; i++) {
      if (i > 0 && i % 4 == 0) {
        formatted.write('-');
      }
      formatted.write(raw[i]);
    }
    return formatted.toString();
  }
}

class _ParsedShare {
  final Uint8List rawBytes;
  final int m;
  final int n;
  _ParsedShare(this.rawBytes, this.m, this.n);
}
